name: babylonlabs/rollup-bsn-contracts/deploy
on:
  push:
    tags:
      - 'v*.*.*'
env:
  CARGO_TERM_COLOR: always
  WORKSPACE: "/home/runner/work/rollup-bsn-contracts/rollup-bsn-contracts"
jobs:
  build_and_upload_contracts:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      pull-requests: read
      contents: write
      deployments: write
      pages: write
      repository-projects: write
      statuses: write
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Build optimised Wasm binaries
      run: "./scripts/optimizer.sh"
    - uses: actions/upload-artifact@v4.1.0
      with:
        path: |-
          artifacts/finality.wasm
          artifacts/checksums.txt
    - name: Show data
      run: |-
        ls -l artifacts
        cat artifacts/checksums.txt
    - name: Zip artifacts
      run: |-
        zip ./finality.wasm.zip artifacts/finality.wasm
    - name: Create a Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Attached there are some build artifacts generated at this tag.
          draft: false
          prerelease: false
    - name: Upload finality
      id: upload-finality
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./finality.wasm.zip
        asset_name: finality.wasm.zip
        asset_content_type: application/zip
    - name: Upload checksums
      id: upload-checksums
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./artifacts/checksums.txt
        asset_name: checksums.txt
        asset_content_type: text/plain
    - name: Build and run schema generator
      run: |-
        (cd ./contracts/finality && cargo run --bin schema)
    - name: Consolidate schemas
      run: |-
        mkdir -p ./schemas
        cp -a ./contracts/*/schema/* ./schemas
    - name: Show data
      run: ls -l ./schemas
    - name: Zip schemas
      run: |-
        zip -r ./schemas.zip schemas/
    - name: Upload schemas
      id: upload-schemas
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./schemas.zip
        asset_name: schemas.zip
        asset_content_type: application/zip
