name: babylonlabs/finality/local-tests
on:
  pull_request:
    branches:
      - '**'
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
jobs:
    # based on https://github.com/bnjbvr/cargo-machete
  machete:
    name: machete
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Machete
        uses: bnjbvr/cargo-machete@main

  local-build-test:
    runs-on: ubuntu-latest
    container:
      image: rust:1.86.0
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Build contracts, check formats, and run unit tests
      run: |
        rustup component add rustfmt
        cargo fmt -- --check
        cargo test --lib

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Set up Go 1.23
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Run e2e tests
      run: ./scripts/e2e_test.sh