name: babylonlabs/rollup-bsn-contracts/wasm-tests-full
on:
  pull_request:
    branches:
      - '**'
env:
  CARGO_TERM_COLOR: always
  WORKSPACE: "/home/runner/work/rollup-bsn-contracts/rollup-bsn-contracts"
jobs:
  wasm-build-check-integration-full:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Build optimised Wasm binaries
      run: "./scripts/optimizer.sh"
    - name: List optimised Wasm binaries
      run: bash -c "ls $WORKSPACE/artifacts/*.wasm"
    - name: Install cosmwasm-check
      run: cargo install --locked --debug --version ^2.0 cosmwasm-check
    - name: Check the Wasm binaries' validity
      run: bash -c "cosmwasm-check --available-capabilities cosmwasm_1_1,cosmwasm_1_2,cosmwasm_1_3,cosmwasm_1_4,cosmwasm_2_0,iterator,staking,stargate,babylon $WORKSPACE/artifacts/*.wasm"
    - name: Integration tests based on CosmWasm
      run: cargo test --test integration
    - name: Install Golang
      uses: actions/setup-go@v4.1.0
      with:
        go-version: 1.23.10
    - name: E2E tests
      run: ./scripts/e2e_test.sh
    - uses: actions/upload-artifact@v4.1.0
      with:
        path: |-
          artifacts/finality.wasm
